version: "3"
services:
  web:
    container_name: confluence_web
    build: ./nginx
    ports:
      - "80:80"
    links:
      - app
  app:
    container_name: confluence_app
    build: ./confluence
    volumes:
      - confluence_appdata:/var/atlassian/application-data/confluence
    links:
      - db
    depends_on:
      - db
  db:
    container_name: confluence_db
    build: ./postgres 
    restart: always
    env_file:
      - postgres/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  confluence_appdata:
  postgres_data:
